"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
palette = "gruvbox_dark"

format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$golang\
$java\
$docker_context\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "bold blue"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"
format = "[$path]($style)[$read_only]($style) "

[directory.substitutions]
Developer = "󰲋 "
Documents = "󰈙 "
Downloads = " "
Music = "󰝚 "
Pictures = " "

[git_branch]
symbol = " "
style = "bold mauve"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold yellow"
format = "[$all_status$ahead_behind]($style) "

[nodejs]
symbol = " "
style = "bold green"
format = "via [$symbol$version]($style) "

[python]
symbol = " "
style = "bold green"
format = "via [$symbol$version(\\($virtualenv\\))]($style) "

[golang]
symbol = " "
style = "bold green"
format = "via [$symbol$version]($style) "

[java]
symbol = " "
style = "bold green"
format = "via [$symbol$version]($style) "

[docker_context]
symbol = " "
style = "bold sapphire"
format = "via [$symbol$context]($style) "
only_with_files = true

[aws]
symbol = " "
style = "bold peach"
format = "on [$symbol$profile]($style) "
disabled = false

[cmd_duration]
min_time = 2000
show_milliseconds = true
format = "took [$duration](bold yellow) "

[line_break]
disabled = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_replace_one_symbol = "[❮](bold lavender)"
vimcmd_replace_symbol = "[❮](bold lavender)"
vimcmd_visual_symbol = "[❮](bold yellow)"

[palettes.gruvbox_dark]
red = "#fb4934"
maroon = "#cc241d"
peach = "#fe8019"
yellow = "#fabd2f"
green = "#b8bb26"
teal = "#8ec07c"
blue = "#83a598"
sapphire = "#83a598"
mauve = "#d3869b"
lavender = "#d3869b"
text = "#ebdbb2"
subtext1 = "#d5c4a1"
subtext0 = "#bdae93"
overlay2 = "#a89984"
overlay1 = "#928374"
overlay0 = "#7c6f64"
surface2 = "#665c54"
surface1 = "#504945"
surface0 = "#3c3836"
base = "#282828"
mantle = "#1d2021"
crust = "#1d2021"
